version: '3'

services:
  caddy:
    image: caddy:2.7.6-alpine
    ports:
      - "88:80"
      - "443:443"
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "caddy_data:/data"
      - "caddy_config:/config"
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
    working_dir: /home/node/app
    volumes:
      - "./frontend/:/home/node/app"
    ports:
      - "3000:3000"
    command: >
      bash -c "npm i
      && npm run dev"
  martin:
    image: maplibre/martin
    ports:
      - 4000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
  redis:
    image: redis
    ports:
      - "6379:6379"
  django:
    build:
      context: ./django
    image: ecolens/django
    ports:
      - "8000:8000"
    volumes:
      - "./django:/usr/src/app"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NBB_CBSO_SUBSCRIPTION_KEY=${NBB_CBSO_SUBSCRIPTION_KEY}
      - DEBUG=1
      #  - ALLOWED_HOST=${SERVER_IP}
    # command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    command: python manage.py runserver 0.0.0.0:8000

  celery:
    image: ecolens/django
    volumes:
      - "./django:/usr/src/app"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: celery -A ecolens worker -l info

  # postgis:
  #   image: postgis/postgis:16-master
  #   environment:
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #   volumes:
  #     - "./db/data:/var/lib/postgresql/data"
  #     - "./db/init-scripts:/docker-entrypoint-initdb.d"
  #   ports:
  #     - "5432:5432"

volumes:
  caddy_data:
  caddy_config:
