# Generated by Django 4.2.3 on 2023-12-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view',
            old_name='point',
            new_name='center',
        ),
    ]
