# Generated by Django 4.2.3 on 2024-01-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_point_view_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('json', 'Geojson')], default='json', max_length=4)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('schema', models.CharField(max_length=255)),
                ('table', models.CharField(max_length=255)),
            ],
        ),
    ]
