# Generated by Django 4.2.3 on 2024-01-26 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_inputsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputSourceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('fail', 'Fail'), ('in_progress', 'In progress')], default='in_progress', max_length=12)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('message', models.CharField(max_length=255, null=True)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.inputsource')),
            ],
        ),
    ]
