# Generated by Django 4.2.3 on 2024-02-28 20:20

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_inputsourceupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressEnterprise',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('source', models.TextField()),
            ],
            options={
                'db_table': 'address_enterprise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('street_name', models.TextField(blank=True, null=True)),
                ('street_number', models.TextField(blank=True, null=True)),
                ('postal_code', models.TextField(blank=True, null=True)),
                ('municipality', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('province', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('dist_fuzzy', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, srid=31370)),
            ],
            options={
                'db_table': 'addresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EconomicalActivityPark',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='LIBELLE', null=True)),
            ],
            options={
                'db_table': 'pre_geoportail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enterprises',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('establishment_number', models.TextField(unique=True)),
                ('enterprise_number', models.TextField(unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('name_commercial', models.TextField(blank=True, null=True)),
                ('name_short', models.TextField(blank=True, null=True)),
                ('form', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('nace_main', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, default=list, null=True, size=None)),
                ('nace_other', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, default=list, null=True, size=None)),
                ('sector', models.CharField(blank=True, choices=[('PRIMARY', 'PRIMARY'), ('SECONDARY', 'SECONDARY'), ('TERTIARY', 'TERTIARY')], max_length=10, null=True)),
                ('address_extra', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('reliability_index', models.IntegerField(blank=True, null=True)),
                ('capakey', models.TextField(blank=True, null=True)),
                ('extra_properties', models.JSONField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, srid=31370)),
            ],
            options={
                'db_table': 'enterprises',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='inputsource',
            name='filenames',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inputsource',
            name='type',
            field=models.CharField(choices=[('json', 'Geojson'), ('shpz', 'ShapefileZipped')], default='json', max_length=4),
        ),
    ]
