# Generated by Django 4.2.3 on 2024-03-13 20:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_addressenterprise_addresses_economicalactivitypark_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NaceCode",
            fields=[
                ("code", models.TextField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("category", models.TextField()),
                ("language", models.TextField()),
            ],
            options={
                "db_table": '"kbo"."code"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WalloniaPlots",
            fields=[
                ("capakey", models.TextField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, db_column="geometry", srid=31370
                    ),
                ),
            ],
            options={
                "db_table": '"plots"."wallonia"',
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Layer",
        ),
        migrations.DeleteModel(
            name="View",
        ),
        migrations.AlterModelTable(
            name="economicalactivitypark",
            table='"ingestion"."pre_geoportail"',
        ),
    ]
